build: update husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,7 +2,7 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 if ! which autocorrect >/dev/null; then
-  echo "Error: autocorrect is not installed." >&2
+  echo "Error: autocorrect is not installed. Please refer to https://github.com/huacnlee/autocorrect#installation for installation." >&2
   exit 1
 fi
 
